apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: wholesale
data:
  NODE_ENV:              "production"
  POSTGRES_HOST:         "postgres-service"
  POSTGRES_PORT:         "5432"
  POSTGRES_DB:           "wholesale_db"
  REDIS_HOST:            "redis-service"
  REDIS_PORT:            "6379"
  MONGO_URI:             "mongodb://mongo-service:27017/wholesale_catalog"
  AI_SERVICE_URL:        "http://ai-service:8000"
  ES_URL:                "http://elasticsearch-service:9200"
  APP_PORT:              "3000"
  AUTH_SERVICE_PORT:     "3001"
  CATALOG_SERVICE_PORT:  "3002"
  ORDER_SERVICE_PORT:    "3003"